CREATE TABLE IF NOT EXISTS cie_prenotazioni (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_code VARCHAR(32) NOT NULL UNIQUE,
    cliente_id INT UNSIGNED NULL,
    cittadino_nome VARCHAR(100) NOT NULL,
    cittadino_cognome VARCHAR(100) NOT NULL,
    cittadino_cf VARCHAR(16) NULL,
    cittadino_email VARCHAR(160) NULL,
    cittadino_telefono VARCHAR(40) NULL,
    comune VARCHAR(150) NOT NULL,
    comune_codice VARCHAR(12) NULL,
    preferenza_data DATE NULL,
    preferenza_fascia VARCHAR(60) NULL,
    stato VARCHAR(32) NOT NULL DEFAULT 'nuova',
    slot_data DATE NULL,
    slot_orario VARCHAR(20) NULL,
    slot_protocollo VARCHAR(80) NULL,
    slot_note TEXT NULL,
    note TEXT NULL,
    operator_id INT UNSIGNED NULL,
    reminder_sent_at DATETIME NULL,
    prenotato_il DATETIME NULL,
    completato_il DATETIME NULL,
    annullato_il DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_cie_stato (stato),
    INDEX idx_cie_comune (comune),
    INDEX idx_cie_created_at (created_at),
    CONSTRAINT fk_cie_prenotazioni_cliente FOREIGN KEY (cliente_id) REFERENCES clienti(id) ON DELETE SET NULL,
    CONSTRAINT fk_cie_prenotazioni_operator FOREIGN KEY (operator_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
