name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          extensions: pdo_mysql

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Validate Composer file
        run: composer validate --no-check-all

      - name: Dump autoload
        run: composer dump-autoload

      - name: Lint PHP syntax
        run: find . -name '*.php' -not -path './vendor/*' -print0 | xargs -0 -n1 php -l

      - name: Placeholder unit tests
        run: composer test
        continue-on-error: true
